Feature: Update footer links
TAKANOME-DEV/BlogHive pull request #28
Opened 2023-01-06 00:29 UTC by dev-phantom

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] ⏩ Revert

## Description

Updated the footer
## Related Tickets & Documents

Feature: Update footer links #27
## Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/72051159/210905411-0dfd1ad0-62aa-467e-bc4c-e9c4bd5b0b46.png)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### 📸 Credits

This pull request template was created by [Open Sauced](https://github.com/open-sauced) 🍕

2023-01-06 00:33 UTC, dev-phantom commented
sorry i  made a mistake in the branch name i though it was a fix

2023-01-06 18:54 UTC, dev-phantom commented
done

2023-01-06 23:03 UTC, TAKANOME-DEV requested changes

2023-01-06 23:03 UTC, TAKANOME-DEV commented on apps/client/src/components/Footer.tsx
> +          <h6 className="text-slate-400 font-bold text-[22px]">Explore</h6>
```suggestion
          <h6 className="text-slate-400 font-bold text-xl">Explore</h6>
```

2023-01-06 23:03 UTC, TAKANOME-DEV commented on apps/client/src/components/Footer.tsx
> +          <h6 className="text-slate-400 font-bold text-[22px]">BlogHive</h6>
```suggestion
          <h6 className="text-slate-400 font-bold text-xl">BlogHive</h6>
```

2023-01-06 23:03 UTC, TAKANOME-DEV commented on apps/client/src/components/Footer.tsx
> +          <h6 className="text-slate-400 font-bold text-[22px]">Support</h6>
```suggestion
          <h6 className="text-slate-400 font-bold text-xl">Support</h6>
```

2023-01-06 23:32 UTC, dev-phantom commented
fixed

2023-01-06 23:40 UTC, dev-phantom commented
fixed

2023-01-07 00:21 UTC, TAKANOME-DEV reviewed
Ready to be merged :fire: 

Just one thing: since there is an issue for the subscribe section (text size and color), I would suggest to revert the changes made in `pages/index.tsx` file

2023-01-07 00:30 UTC, dev-phantom commented
Ive  reverted  the changes

2023-01-07 00:38 UTC, TAKANOME-DEV commented
Awesome :tada: Thanks for your contribution :rocket:

2023-01-07 00:38 UTC, merged