Feature: update text size and color for the subscribe card
TAKANOME-DEV/BlogHive pull request #29
Opened 2023-01-06 19:36 UTC by dev-phantom

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] ⏩ Revert

## Description

I removed the former input and button on the subscriber card and added a new one with a better design
I also updated text size and color for the subscribe card
## Related Tickets & Documents

Fixed #24 
## Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/72051159/211086458-3b7bc937-e6f0-4c3a-813d-69fa3692172c.png)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### 📸 Credits

This pull request template was created by [Open Sauced](https://github.com/open-sauced) 🍕

2023-01-06 23:52 UTC, TAKANOME-DEV commented
Hey @dev-phantom, Thanks for your contribution.
Since there is an issue for the footer and the `input + button` located in the subscribe section, I would suggest to revert those changes and only include the one mentioned in the issue #24

2023-01-06 23:53 UTC, TAKANOME-DEV requested changes
Minor adjustment here:

2023-01-06 23:53 UTC, TAKANOME-DEV commented on apps/client/src/pages/index.tsx
>            <div className="flex max-w-2xl flex-col items-center justify-center gap-8 p-8">
```suggestion
          <div className="flex max-w-3xl flex-col items-center justify-center gap-8 p-8">
```

2023-01-07 00:29 UTC, dev-phantom commented
@TAKANOME-DEV fixed

2023-01-07 00:41 UTC, TAKANOME-DEV commented
Great, just resolve the conflicts in this PR and it will be ready to be merged

2023-01-07 00:54 UTC, dev-phantom commented
Conflict Resolved

2023-01-07 00:57 UTC, TAKANOME-DEV approved these changes
Great :+1: Thanks for the contribution

2023-01-07 00:57 UTC, merged